{{ $GlovalValues := .Values }}
  {{ $globalName := .Release.Name }}
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{.Release.Name}}-filebeat
spec:
  type: filebeat
  version: {{.Values.elastic.version}}
  elasticsearchRef:
    name: {{.Values.elastic.releaseName}}-elasticsearch
    namespace: {{.Values.elastic.namespace}}
  kibanaRef:
    name: {{.Values.elastic.releaseName}}-kibana
    namespace: {{.Values.elastic.releaseName}}
  config:
    filebeat.inputs:
      - type: filestream
        paths: /tmp_logs/**/*
        parsers:
          - ndjson:
            overwrite_keys: true
            add_error_key: true
            expand_keys: true
  deployment:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
        containers:
          - name: filebeat
            volumeMounts:
              - name: logs
                mountPath: /tmp_logs
        volumes:
          - name: logs
            persistentVolumeClaim:
              claimName: {{ $globalName }}-pvc