{{ $GlovalValues := .Values }}
  {{ $globalName := .Release.Name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $globalName }}-ca-certs
type: Opaque
data:
  {{ range $key,$value := $GlovalValues.gloval.cert}}
  {{$key}}: {{$value}}
  {{end}}
